  var AREA_INFO = {
    'bankside': { name:'Bankside', postcodes:'SE1',
      overview:'Bankside runs along the Thames path between Blackfriars and London Bridge, on land that once sat outside the City of London\'s jurisdiction and its laws. That old freedom from the City\'s rules is why the area became Tudor London\'s entertainment district, and why its riverside skyline is now dominated by a former power station turned into one of the world\'s most visited galleries.',
      history:'Bankside took its name from "the banke," marshland reclaimed by the Bishop of Winchester as part of the Liberty of the Clink. Because it sat outside the City\'s authority, the taverns, brothels and playhouses the City banned flourished here instead &mdash; the Rose, the Swan, the Hope and, from 1599, Shakespeare\'s Globe. The area declined into wharves and warehouses once the theatres closed, and stayed industrial until Bankside Power Station shut in 1981. Its conversion into Tate Modern, alongside a replica Globe built in the late 1990s and the Millennium Bridge opened in 2000, turned a working riverside back into one of London\'s busiest cultural quarters.',
      image:'' },

    'bermondsey': { name:'Bermondsey', postcodes:'SE1, SE16',
      overview:'Bermondsey sits on the south bank between Rotherhithe and Southwark, a district that spent the 19th and early 20th centuries as one of London\'s great manufacturing quarters &mdash; leather especially, but also biscuits, jam and canned food &mdash; before its wharves and warehouses were converted into flats and studios from the 1980s onward.',
      history:'An abbey founded here in 1082 shaped the area for centuries, its monks draining the marsh and cutting St Saviour\'s Dock. By the 19th century Bermondsey had become a byword for heavy industry: the Leather Market opened in 1833, Peek Frean began baking biscuits at Dockhead in 1857, and the world\'s first commercial food-canning business, Donkin, Hall and Gamble, had already started up on Blue Anchor Lane in 1812. The overcrowded slum of Jacob\'s Island, made famous by Dickens in Oliver Twist, stood alongside this industry. Bombing and the decline of river trade emptied the warehouses by the 1960s; their conversion into housing from the 1980s, and the opening of Bermondsey Underground station in 2000, remade the area into one of London\'s more fashionable postcodes.',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Bermondsey%2C_July_2023_07.jpg/500px-Bermondsey%2C_July_2023_07.jpg' },

    'bexley': { name:'Bexley', postcodes:'DA5',
      overview:'Bexley, sometimes called Bexley Village or Old Bexley to separate it from the wider borough that takes its name, is a small former Kentish market settlement in the Cray valley that stayed largely rural until well into the 20th century.',
      history:'Bexley was an ancient Kent parish under the Diocese of Rochester for most of its existence, its name meaning "boxtree wood." It only gained formal urban status in 1894, becoming Bexley Urban District, and was raised to municipal borough status in 1935. When the Greater London Council replaced the London County Council in 1965, Bexley merged with Erith, Crayford and part of Chislehurst and Sidcup to form the modern London Borough of Bexley, with the old village at its historic core still tracing its lanes around Hall Place and the River Cray.',
      image:'' },

    'bexleyheath': { name:'Bexleyheath', postcodes:'DA6',
      overview:'Bexleyheath grew from open heath and scrubland into a Victorian railway suburb, and it owes its most famous building &mdash; the Red House &mdash; to the Arts and Crafts movement that William Morris and Philip Webb effectively founded here in 1859.',
      history:'The Romans laid Watling Street straight across the heath on their way from London to Dover, and the route still runs through the middle of the modern town. Bexleyheath itself stayed mostly common land until the 1814 enclosure, after which Sir John Boyd\'s Danson House, built in 1766, anchored one end of the parish and Philip Webb\'s Red House, built in 1859 for William Morris, anchored the other. Morris lived there only five years before selling up in 1865, but the house\'s influence on British design proved lasting. The Bexleyheath railway line, promoted in the 1880s, turned the heath into a proper suburb, and a clock tower raised in 1912 to mark George V\'s coronation still stands at its centre; the town became the administrative base of the new London Borough of Bexley in 1965.',
      image:'' },

    'blackheath': { name:'Blackheath', postcodes:'SE3',
      overview:'Blackheath is exactly what it sounds like &mdash; a wide, open heath, one of the highest points in south-east London &mdash; with a history of pulling large, often unruly crowds long before it became a genteel Georgian and Victorian suburb.',
      history:'The heath was already a meeting place for the local Anglo-Saxon "hundred," recorded as Blachehedfeld in 1166, and a Roman road, later Watling Street, crossed straight through it. Its flat, open ground made it a natural rallying point: Wat Tyler\'s rebels gathered here in 1381, Jack Cade\'s followers in 1450, and Cornish rebels were defeated on its western slope at the Battle of Deptford Bridge in 1497. Kings met visiting dignitaries on the heath too &mdash; Henry IV received the Byzantine emperor here around 1400 &mdash; while by the 18th century it had a rather different reputation as a haunt of highwaymen. Housing crept in from the 1850s as new parishes were carved out, and management of the heath itself passed from the Earl of Dartmouth to the Metropolitan Board of Works in 1871, and eventually to Greenwich and Lewisham councils in 1986.',
      image:'' },

    'brockley': { name:'Brockley', postcodes:'SE4',
      overview:'Brockley is a compact grid of Victorian and Edwardian streets in Lewisham, kept largely intact by a conservation area designation and a resident-led preservation society, and voted the best place to live in London by the Sunday Times in 2021.',
      history:'The name comes from "Broca\'s woodland clearing," and a small monastery briefly stood here in the late 12th century before relocating to Sussex in 1208. Brockley stayed agricultural, known locally for its rhubarb, until the railway arrived &mdash; the Croydon Canal of 1809 gave way to a line through the area, and Brockley station opened in 1871. The Tyrwhitt-Drake family then developed grand villas and terraces for factory owners and City clerks, drawing residents like the actress Lillie Langtry. After the First World War many of the big houses were split into flats, and postwar the area became a landing point for Windrush-generation immigrants &mdash; five of the ship\'s original passengers gave Wickham Road as their destination in 1948. A conservation area was declared in 1974, and the East London Line\'s arrival in 2010 brought a fresh wave of investment.',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/South_London%2C_The_%27Brockley_Jack%27_-_geograph.org.uk_-_3099356.jpg/500px-South_London%2C_The_%27Brockley_Jack%27_-_geograph.org.uk_-_3099356.jpg' },

    'camberwell': { name:'Camberwell', postcodes:'SE5',
      overview:'Camberwell grew from a village around St Giles\' Church, with mineral springs that once drew Londoners out for the air, into a dense inner-city district that mixes handsome Georgian squares with the more bohemian pull of its art school.',
      history:'Camberwell appears in the Domesday Book as a settled parish, and stayed a semi-rural retreat, its wells and open common drawing visitors, well into the 19th century. The railway\'s arrival in the 1860s changed that decisively: the population, just 7,059 in 1801, had reached 54,667 by 1851 and kept climbing as terraces filled the old fields. Administratively the parish moved from Surrey into the new County of London in 1889 and became the Metropolitan Borough of Camberwell in 1900, before being folded into the London Borough of Southwark in 1965. Camberwell College of Arts, meanwhile, has given the area a long-running reputation as a training ground for British artists &mdash; Pink Floyd\'s Syd Barrett among its less conventional alumni.',
      image:'' },

    'catford': { name:'Catford', postcodes:'SE6',
      overview:'Catford is Lewisham\'s administrative and shopping heart, a district whose slightly puzzling name is matched by its equally odd landmark &mdash; a giant fibreglass cat perched above a 1970s shopping centre.',
      history:'No one is entirely sure where the name comes from &mdash; theories range from a cattle crossing on the River Ravensbourne to wild cats using the same ford &mdash; but it only spread from the small village around Rushey Green after Catford Bridge station opened in the 1850s and pulled development toward it. The Broadway Theatre, an Art Deco concert hall with a distinctive copper dome, opened in 1932 and survives as a Grade II listed building. Much of the rest of Catford\'s centre was rebuilt in the 1960s and 70s: Eros House went up in 1962, a new civic suite replaced the Victorian town hall in 1968, and Milford Towers followed soon after. The Excalibur Estate in nearby Bellingham, built as emergency post-war prefab housing, went on to become Britain\'s largest surviving prefab estate.',
      image:'' },

    'charlton': { name:'Charlton', postcodes:'SE7',
      overview:'Charlton is a former riverside village between Greenwich and Woolwich, largely swallowed by 19th- and 20th-century docks and industry, but still centred on one of the finest Jacobean houses in London.',
      history:'Recorded in the Domesday Book as "Cerletone," Charlton was held for centuries by Bermondsey Abbey before passing into private hands. Sir Adam Newton, tutor to Prince Henry, built Charlton House in 1607&ndash;12, and James I is said to have planted a mulberry tree there in 1608 to encourage silk production. From the 17th century the village was also known for its raucous Horn Fair, held every October and eventually abolished in 1872 for rowdiness. Heavy industry moved in through the 19th century &mdash; the Siemens Brothers Telegraph Works from 1863, later J. Stone &amp; Co\'s wartime propeller foundry &mdash; and Charlton Athletic Football Club was founded on the riverside in 1905 before moving to The Valley in 1919. The area became part of the new London Borough of Greenwich in 1965.',
      image:'' },

    'crystal palace': { name:'Crystal Palace', postcodes:'SE19, SE20',
      overview:'Crystal Palace takes its name from the vast glass exhibition hall that stood here from 1854 until a fire destroyed it in 1936, and though the building is long gone, the park, the concrete dinosaurs and the district\'s slightly bohemian character all still trade on its memory.',
      history:'Before the Palace arrived, the high ridge here was known as Sydenham Hill, part of the ancient Great North Wood. Joseph Paxton\'s glass-and-iron exhibition hall, built for the 1851 Great Exhibition in Hyde Park, was dismantled and re-erected here in enlarged form in 1854, complete with fountains, a concert hall and the newly commissioned Crystal Palace Dinosaurs. Two railway stations grew up to serve the crowds it drew. The Palace burned down on 30 November 1936, a fire visible across much of London, and the site became a public park; its high-level station closed in 1954 and was demolished in 1961. In 2022 the Sunday Times named the district London\'s best place to live.',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Mantellodon_in_Crystal_Palace_Park.jpg/500px-Mantellodon_in_Crystal_Palace_Park.jpg' },

    'deptford': { name:'Deptford', postcodes:'SE8',
      overview:'Deptford grew up around England\'s first royal dockyard, founded by Henry VIII in 1513, and though the dockyard itself closed in 1869, the area has kept its working-river character through markets, studios and a long list of maritime firsts.',
      history:'The name comes from a "deep ford" across the River Ravensbourne, on the old pilgrim route to Canterbury. Henry VIII\'s dockyard made Deptford a genuinely global address: Elizabeth I knighted Francis Drake here in 1581, Peter the Great studied shipbuilding at Sayes Court in 1698, and the diarist John Evelyn lived at the same house for decades. The dockyard closed in 1869 as warship building declined, and the site became first a cattle market, then a naval victualling yard. Deptford suffered heavily in the Second World War &mdash; a V-2 rocket killed 168 people at a New Cross Woolworths in 1944 &mdash; and the last working dock, Convoys Wharf, finally shut in 2000, since redeveloped for housing alongside the area\'s flea markets and artist studios.',
      image:'' },

    'dulwich': { name:'Dulwich', postcodes:'SE21',
      overview:'Dulwich has stayed remarkably village-like for a place a few miles from central London, thanks to a private estate founded by the actor Edward Alleyn in 1619 that still owns and manages much of the land, including England\'s oldest purpose-built public art gallery.',
      history:'Dulwich was granted as a hamlet by King Edgar in 967 and later passed to Bermondsey Abbey, before Henry VIII sold it to a goldsmith in 1538. In 1605 the actor-manager Edward Alleyn bought the manor and in 1619 founded the College of God\'s Gift, a charitable foundation that eventually split into Dulwich College and Alleyn\'s School and still endows the wider Dulwich Estate today. The Georgian era brought curious visitors for the area\'s "purgative" spring water, and a murdered recluse known as the Dulwich Hermit; the Victorian era brought Dulwich Picture Gallery, built in 1811&ndash;14 and generally reckoned to be England\'s first public art gallery, plus a wave of railway-driven housebuilding that took the population from 1,632 in 1851 to over 10,000 by 1901.',
      image:'https://upload.wikimedia.org/wikipedia/commons/9/9b/Dulwich_College%2C_College_Road%2C_Dulwich._-_geograph.org.uk_-_58443.jpg' },

    'east dulwich': { name:'East Dulwich', postcodes:'SE22',
      overview:'East Dulwich is Dulwich\'s less formal neighbour &mdash; Victorian terraces built on College land from the 1870s onward, and a Lordship Lane high street that has never quite settled on a single identity, from Georgian farmland to today\'s gastropubs and gentrification.',
      history:'The land was part of the ancient Dulwich manor, first recorded in 967, but stayed largely farms and market gardens until the London, Chatham and Dover Railway arrived in 1863. East Dulwich station opened in 1868 and Lordship Lane station in 1871, and in the decade that followed over 5,000 houses went up as the area turned from hamlet to Victorian suburb almost overnight. Several churches, a hospital, public baths, a fire station and a library followed through the 1880s and 90s, along with Dulwich Park and Peckham Rye Park. The area moved from the Metropolitan Borough of Camberwell into the new London Borough of Southwark in 1965, and Lordship Lane\'s independent shops and restaurants have driven a steady gentrification since.',
      image:'' },

    'elephant': { name:'Elephant &amp; Castle', postcodes:'SE1, SE17',
      overview:'Elephant and Castle takes its name from an old coaching inn and now describes a whole junction and district around it &mdash; one of the most heavily and repeatedly rebuilt corners of south London, currently in the middle of yet another major redevelopment.',
      history:'The parish, recorded in the Domesday Book under the Archbishop of Canterbury\'s Walworth manor, only picked up the "Elephant and Castle" name from its coaching inn in 1765. The area boomed once Westminster Bridge opened new routes south in the 1750s, and by the late 19th century its department stores had it nicknamed "the Piccadilly of South London." Trams, then the Tube &mdash; London\'s first deep-level line reached here in 1890 &mdash; kept the junction busy, but the Second World War hit it hard, and much of what survived was cleared for brutalist postwar reconstruction: the 1965 shopping centre, sold as Europe\'s first covered mall, and the Heygate Estate, completed in 1974. Both the centre and the Heygate have since been demolished in turn, part of a redevelopment begun in the 2000s and still ongoing.',
      image:'' },

    'eltham': { name:'Eltham', postcodes:'SE9',
      overview:'Eltham holds two of south-east London\'s more unlikely buildings within a few streets of each other &mdash; a moated medieval royal palace and a 1930s Art Deco mansion &mdash; inside a suburb that still keeps an unusually large amount of green space for inner London.',
      history:'Eltham Palace was a royal residence from the 13th century, hosting a public Christmas under Henry III in 1270 and parliaments under Edward III in the 1370s. Well Hall, another manor within the parish, later housed the Tudor scholar Margaret Roper and, much later, the socialist writers Hubert Bland and Edith Nesbit. Eltham remained part of Kent until 1889, then passed through the Metropolitan Borough of Woolwich before joining the London Borough of Greenwich in 1965. The Bexleyheath railway line, opened in 1895, triggered decades of suburban estate-building, from Archibald Cameron Corbett\'s Edwardian houses to the wartime Progress Estate of 1915 and further council estates into the 1960s &mdash; all wrapped around a medieval palace that Stephen Courtauld dramatically remodelled in Art Deco style in the 1930s.',
      image:'' },

    'forest hill': { name:'Forest Hill', postcodes:'SE23',
      overview:'Forest Hill sits on the steep slope above the old Great North Wood, a district shaped almost entirely by two 19th-century arrivals &mdash; a railway and a museum &mdash; that turned a patch of forest into a distinctly varied stretch of Victorian and Edwardian streets.',
      history:'The name simply describes what was here before development &mdash; woodland, part of the ancient Great North Wood. A canal opened through the area in 1809 but failed commercially and was converted into a railway by 1839, and once the Crystal Palace relocated to neighbouring Sydenham in 1854, Forest Hill filled in quickly with new housing. London\'s oldest surviving swimming pool opened on Dartmouth Road in 1884, and in 1901 the tea merchant Frederick Horniman gave his private museum and gardens to the public, creating the Horniman Museum &mdash; still the district\'s best-known landmark, home to an eccentric mix of taxidermy, musical instruments and the world\'s first mounted walrus.',
      image:'https://upload.wikimedia.org/wikipedia/commons/1/12/Horniman_bandstand_skyline.jpg' },

    'gipsy hill': { name:'Gipsy Hill', postcodes:'SE27',
      overview:'Gipsy Hill is a steep, leafy neighbourhood between Dulwich and Crystal Palace, named for the Romani people once recorded camping on this stretch of common land, and shaped almost entirely by its railway station and the large council estates built on its slopes in the 20th century.',
      history:'Samuel Pepys recorded his wife visiting "the gypsies at Lambeth" in 1668, and the district\'s Romani associations lingered in its name long after the last encampments left. Gipsy Hill railway station opened in 1856 and quickly drew large private mansions, most later subdivided into flats, while the reorganisation of London\'s parishes in 1889 finally untangled the area\'s old split between Lambeth and Camberwell jurisdictions. The Central Hill Estate, a low-rise council development that follows the contours of the hillside, was built between 1967 and 1974 by the Greater London Council; one of its blocks, Pear Tree House, even concealed an 18-room nuclear bunker built during the Cold War, between 1963 and 1966.',
      image:'' },

    'greenwich': { name:'Greenwich', postcodes:'SE10',
      overview:'Greenwich has been royal, maritime and scientific ground for the best part of a thousand years &mdash; the site of a Tudor palace, the Royal Observatory that fixed the meridian of world time, and the Old Royal Naval College &mdash; and is now a UNESCO World Heritage Site.',
      history:'The name is recorded from 918, and a royal residence stood here from at least the 1300s; Henry VIII and his sisters were born at the Palace of Placentia, and Elizabeth I\'s Council planned the defence against the Spanish Armada from Greenwich in 1588. The Tudor palace fell into ruin after the Civil War, and Charles II began a replacement that Christopher Wren eventually completed, from 1696, as the Royal Hospital for Seamen &mdash; now the Old Royal Naval College. Charles II also founded the Royal Observatory in 1675, whose meridian line was adopted as the world\'s Prime Meridian in 1884. Greenwich\'s railway, opened in 1838, was London\'s first, and the National Maritime Museum opened in the former Royal Hospital School buildings in 1937. The borough received Royal status in 2012, recognising its royal, maritime and scientific history all at once.',
      image:'' },

    'herne hill': { name:'Herne Hill', postcodes:'SE24',
      overview:'Herne Hill is a district of terraced Victorian streets straddling Lambeth and Southwark, built up around its own railway station from the 1860s, and known today for Brockwell Park and its 1891 velodrome.',
      history:'The land here formed part of the Manor of Milkwell from at least 1291, a mix of farms and woodland split between the Camberwell and Lambeth parishes. Samuel Sanders began leasing plots to wealthy families from 1783, and by the mid-19th century Herne Hill was a prosperous merchant suburb of substantial villas &mdash; the young John Ruskin grew up in one of them from the age of four. The railway\'s arrival in 1862 brought demand for smaller housing, and the terraced streets that define the area today mostly date from the following decades. Herne Hill Velodrome, opened in 1891, went on to host the track cycling at the 1948 London Olympics, and remains one of the oldest cycling tracks still in regular use anywhere in the world.',
      image:'' },

    'honor oak': { name:'Honor Oak', postcodes:'SE23',
      overview:'Honor Oak is a quiet, leafy hilltop suburb named after a tree Elizabeth I is said to have picnicked beneath, whose main landmark today is what was, at completion, the largest brick-built underground reservoir in the world.',
      history:'Local legend places Elizabeth I picnicking under an oak on One Tree Hill in 1602, giving the hill and the surrounding streets their name, though the hill\'s history goes back much further &mdash; it\'s also linked to Boudica\'s final defeat by the Romans and later served as a highwayman\'s lookout. Development followed the railway from the 1860s, and in 1896 a plan to build a golf course on One Tree Hill provoked riots and demonstrations that kept the land public instead. The vast Honor Oak Reservoir was built beneath the hill between 1901 and 1909, and a beacon erected for George V\'s Silver Jubilee in 1935 has been relit for royal occasions since. The area\'s station joined the London Overground network in 2010.',
      image:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/The_Honor_Oak%2C_One_Tree_Hill.JPG/500px-The_Honor_Oak%2C_One_Tree_Hill.JPG' },

    'lee': { name:'Lee', postcodes:'SE12',
      overview:'Lee is a quiet suburb between Lewisham and Eltham, better known for the people who used to live and are buried here &mdash; three Astronomers Royal among them &mdash; than for anything still standing.',
      history:'Domesday Book records Lee as a small area of farmland in extensive woodland, and it stayed a modest village clustered around a green until well into the 19th century. St Margaret\'s churchyard became the burial place of three successive Astronomers Royal &mdash; Edmond Halley in 1742, Nathaniel Bliss and John Pond &mdash; and in 1837 the watercolourist Robert Cocking died in a field here in the world\'s first recorded fatal parachute jump, having descended from a balloon launched at Vauxhall Gardens. The railway reached Lee in 1866, prompting the usual wave of Victorian building, and the parish was formally merged into Lewisham in 1904. The 1960s brought the Leegate shopping centre, built over part of the old village green.',
      image:'' },

    'lewisham': { name:'Lewisham', postcodes:'SE13',
      overview:'Lewisham is the borough\'s own high street and transport hub, a district rebuilt hard after being devastated by a V-1 flying bomb in 1944, and rebuilt again more recently around its DLR and rail interchange.',
      history:'The name is recorded from 862, and by 918 the manor had been granted, along with Greenwich, to a Ghent abbey &mdash; a grant later confirmed by successive Saxon kings. Lewisham stayed part of Kent until 1889, its village life centred on St Mary\'s Church at Ladywell before the arrival of the North Kent railway line in 1849 pulled development toward the modern high street. A clock tower raised in 1900 to mark Victoria\'s Diamond Jubilee still stands there. The Second World War brought devastation &mdash; a V-1 struck the town centre in 1944, killing 51 people &mdash; and 1957 brought further tragedy when a rail crash near St Johns killed 90. The 1977 Battle of Lewisham, a clash between the National Front and thousands of counter-demonstrators, was a defining moment in the area\'s postwar history, and Lewisham became the seat of its own London borough in 1965.',
      image:'' },

    'new cross': { name:'New Cross', postcodes:'SE14',
      overview:'New Cross takes its name from an 18th-century tollgate and today is best known as Goldsmiths\' postcode &mdash; a district with a long, sometimes turbulent history of music, squatting and protest.',
      history:'Recorded in the Domesday Book as Hatcham, the area only became "New Cross" after a tollgate was built here in 1718. The Haberdashers\' Company developed much of the land from the 17th century, and by the late 1800s New Cross had become a dense tangle of railway lines and workshops, including the Hatcham Iron Works. A V-2 rocket destroyed a Woolworths store on New Cross Road in November 1944, killing 168 people &mdash; the worst single V-weapon strike of the war on London. The area saw major unrest twice more in the following decades: the 1977 Battle of Lewisham, when anti-fascist demonstrators blocked a National Front march, and the New Cross house fire of January 1981, in which 13 young Black partygoers died in circumstances that triggered the UK\'s largest-ever political mobilisation of Black Britons.',
      image:'' },

    'nunhead': { name:'Nunhead', postcodes:'SE15',
      overview:'Nunhead is a former working-class suburb built around one of London\'s "Magnificent Seven" Victorian cemeteries, wild enough in places that it\'s easy to forget it\'s inside the M25.',
      history:'The name is first recorded in a 1583 deed, its origin uncertain &mdash; most likely a tavern sign, though local legend prefers a beheaded nun. It stayed a scatter of buildings around a green until Victorian development filled it in through the 19th century: almshouses in 1834, a new parish church, St Antholin\'s, in 1877, and a population that had reached nearly 11,000 by 1887. Nunhead Cemetery, opened as one of the ring of large private cemeteries built around London in the 1840s, remains the district\'s best-known feature. St Antholin\'s was bombed in 1940, restored in the 1950s, and eventually sold to a Pentecostal congregation in 2001 after being declared redundant by the Church of England.',
      image:'' },

    'peckham': { name:'Peckham', postcodes:'SE15',
      overview:'Peckham is one of the most ethnically diverse districts in Britain, a market street and a converted multi-storey car park at its social centre, that has swung from Georgian gentility through severe postwar deprivation to a fast-moving regeneration since the 1990s.',
      history:'Recorded in the Domesday Book, Peckham was a wealthy residential village by the 16th century, with market gardens supplying London through the 18th. The railway reached Peckham Rye in 1865, and Rye Lane grew into a major shopping street, anchored by the department store Jones &amp; Higgins from 1867. The 20th century brought hardship: the North Peckham Estate, built in the postwar rebuilding, became one of the most deprived estates in western Europe, and the murder of ten-year-old Damilola Taylor there in 2000 drew national attention to the area\'s problems. A &pound;290 million regeneration programme from the late 1990s, including the award-winning Peckham Library, has since remade much of the district, alongside a well-documented influx of new residents and businesses.',
      image:'' },

    'penge': { name:'Penge', postcodes:'SE20',
      overview:'Penge is a former Battersea manor hamlet turned fashionable Victorian suburb, boosted by its closeness to the relocated Crystal Palace and, more darkly, briefly notorious for two 19th-century murders.',
      history:'The name is recorded as far back as 1067, from a Brittonic phrase meaning roughly "head of the wood." Penge remained a small hamlet with a large common, attached to the manor of Battersea, until the 1827 Inclosure Act enclosed the common and the London and Croydon Railway arrived in 1839. Large villas went up through the 1850s and 60s as the district cashed in on its proximity to the newly relocated Crystal Palace, before two grim killings &mdash; the 1875 murder of Frederick Hunt\'s family and the 1877 starvation of Harriet Staunton, the so-called Penge Mystery &mdash; briefly made national headlines. Administratively Penge was shifted from Surrey to Kent in 1900, becoming its own urban district, before being folded into the London Borough of Bromley in 1965.',
      image:'' },

    'rotherhithe': { name:'Rotherhithe', postcodes:'SE16',
      overview:'Rotherhithe sits on a bend in the Thames opposite Wapping, a former Elizabethan shipbuilding and docking district whose warehouses have mostly been converted into flats since the docks closed in the 1970s.',
      history:'The name is Anglo-Saxon for "landing-place for cattle," first recorded around 1105. Shipyards operated here from at least 1702, and the area is where the Mayflower is said to have set sail in 1620 on its way to America. Brunel\'s Thames Tunnel, the first ever built under a navigable river, opened beneath Rotherhithe in 1843 and was converted to railway use in 1869. The docks that came to dominate the peninsula suffered catastrophic bomb damage on the first night of the Blitz in September 1940, when burning timber stocks produced what witnesses called the most intense single fire seen in Britain up to that point. The docks finally closed and were filled in during the 1980s, since when Rotherhithe has become a quieter, largely residential corner of the borough, helped by the Jubilee line\'s arrival in 1999.',
      image:'' },

    'sydenham': { name:'Sydenham', postcodes:'SE26',
      overview:'Sydenham is the hill above Crystal Palace Park, an area that boomed as a fashionable Victorian suburb once the Crystal Palace itself relocated here in 1854, and has kept trading &mdash; a little wistfully &mdash; on the shadow of a building that burned down in 1936.',
      history:'Originally a scattering of cottages called Sippenham, Sydenham grew after medicinal springs were discovered in what\'s now Wells Park in the 1640s. A canal opened in 1809 failed within decades and was converted into a railway by 1839, but it was the arrival of the Crystal Palace in 1854 that transformed the area, drawing department stores, a children\'s hospital and a wave of grand villas. Notable residents settled on the strength of that reputation, including a young John Logie Baird, who built a television laboratory here in the 1930s, and Ernest Shackleton, who grew up on Westwood Hill. The Palace burned down in 1936 and the area\'s fortunes cooled with it, though its Victorian streets and the site of the world\'s first purpose-built hospice, St Christopher\'s, opened in 1967, remain.',
      image:'' },

    'walworth': { name:'Walworth', postcodes:'SE17',
      overview:'Walworth is dense Victorian terracing off the Old Kent Road, a working-class district that the guidebooks tend to skip, with a long history as a centre for Irish immigration and, more recently, major regeneration.',
      history:'Recorded in the Domesday Book as "Waleorde," Walworth stayed largely rural until the 19th century, when it became known for the Royal Surrey Zoological Gardens, a rival to London Zoo that operated from 1831 until 1856. Charlie Chaplin was born here in 1889, and the comic actor\'s early life among Walworth\'s poverty later shaped much of his screen work. St Peter\'s Church, designed by Sir John Soane, was built around 1825, and Walworth Town Hall became the headquarters of the Metropolitan, and later the London, Borough of Southwark from 1900. Recent decades have brought heavy redevelopment, including the demolition of the Heygate Estate and ongoing regeneration around the Aylesbury Estate.',
      image:'' },

    'woolwich': { name:'Woolwich', postcodes:'SE18',
      overview:'Woolwich grew up around one of Henry VIII\'s royal dockyards and went on to become one of Britain\'s great centres of military manufacturing at the Royal Arsenal &mdash; a history now being reworked into riverside flats, cultural venues and a free ferry that\'s been running since 1889.',
      history:'People have lived on this stretch of the Thames since at least the Iron Age, but Woolwich\'s modern story begins in 1512, when Henry VIII founded a royal dockyard here to build his flagship. The Board of Ordnance began testing guns at the same site &mdash; known as the Warren &mdash; from the 1650s, and it grew into the Royal Arsenal, formally named in 1805, alongside the Royal Regiment of Artillery (formed 1716), the Royal Military Academy (1741) and vast barracks. At its Napoleonic-era peak the Arsenal, dockyard and garrison together employed thousands, and the population climbed from a few hundred around 1500 to over 40,000 by 1861. The dockyard closed in 1869, and the Arsenal itself finally shut in 1994, part of a long post-war industrial decline that also saw the closure of the Siemens cable works. Since then the old Arsenal site has been redeveloped as housing and a cultural quarter, alongside newer, harder history &mdash; the Thames Barrier, completed just downstream in 1984, and the murder of Lee Rigby near the barracks in 2013. Neighbouring Shooter\'s Hill, part of the same postcode, adds its own oddities: a Bronze Age burial mound, a Georgian folly built to commemorate a naval victory in India, and a road once so plagued by highwaymen it gave the hill its name.',
      image:'' }
  };
